# Site settings
title: Tyler J. Durden
email: tylerjdurden@tamu.edu
url: https://tylerjdurden.github.io
description: "Tyler J. Durden's personal site and portfolio!"
skills: "Computer Science Enthusiast • Hackathon Hacker • Music Lover"
meta_author: Durden Tyler

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Tyler J. Durden
  location: Address
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  - title: github
    url: http://github.com/tylerjdurden
  - title: stack-overflow
    url: http://stackoverflow.com/users/6505822/tyler-durden
  - title: linkedin
    url: http://linkedin.com/in/tdurden
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  

# Postal address (add as many lines as necessary)
address:
  - line: 907 Cross St
  - line: Apt 0521
  - line: College Station, TX 77840

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'
credits: 'Created using Bootstrap (Thanks, Twitter!) and Jekyll (Thanks, Tom Preston-Werner!)'

# Build settings
markdown: kramdown
permalink: pretty
